---
title: "K-Nearest Neigbors"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(class)
library(psych)
```

```{r}
fdata<-read.table("football_data.txt", header = T) 
head(fdata)

#labels:  1:  high school football players, 
#         2: college football players, 
#        3:  non-football players in college

```


```{r}
cor(fdata)

pairs.panels(fdata[2:7],
             gap=0,
             bg=c("green", "blue", "red")[fdata$group],
             pch=21)
```


```{r}
#Partition for training and  test data
set.seed(100)
ind <- sample(2, nrow(fdata),replace=T, prob = c(0.7,0.3))
train <- fdata[ind==1,]
test  <- fdata[ind==2,]
train.group <- train$group
```

```{r}
# Model Fit

knn.pred =knn(train,test, train$group, k=4)
knn.pred
```


```{r}
#Accuracy Probability

#Accuracy on test data
mean(knn.pred == test$group)

```


```{r}
#Confusion Matrix for Test Data

table(knn.pred,test$group)

```

```{r}
#Analysis for misclassiffed data
length(test$group)
test$group

wp <- which(knn.pred != test$group)
wp

test[wp,]

```


```{r}
```


```{r}
```

```{r}
```

